#! /usr/bin/env python
# coding:utf-8

import sqlite3

DB_FILE = 'w_seiyu_bot.sqlite'

SEIYU = [
'阿澄佳奈,asumi_kana',
'井口裕香,iguchi_yuka',
'竹達彩奈,taketatsu_ayana',
'戸松遥,tomatu_haruka',
'豊崎愛生,toyosaki_aki',
'寿美菜子,kotobuki_minako',
'花澤香菜,hanazawa_kana',
'高垣彩陽,takagaki_ayahi',
'喜多村英梨,kitamura_eri',
'加藤英美里,kato_emiri',
'悠木碧,yuki_aoi',
'三森すずこ,mimori_suzuko',
'内田真礼,uchida_maya',
'伊藤かな恵,ito_kanae',
'佐藤聡美,sato_satomi',
'小倉唯,ogura_yui',
'三上枝織,miakmi_shiori',
'大久保瑠美,okubo_rumi',
'津田美波,tsuda_minami',
'大坪由佳,otubo_yuka',
'藤田咲,fujita_saki',
'下田麻美,shimoda_asami',
'井上麻里奈,inoue_marina',
'上坂すみれ,uesaka_sumire',
'茅野愛衣,kayano_ai',
'小松未可子,komatsu_mikako',
'東山奈央,toyama_nao',
'早見沙織,hayami_saori',
'佐倉綾音,sakura_ayane',
'橘田いずみ,kitta_izumi',
'斎藤千和,saito_chiwa',
'田村ゆかり,tamura_yukari',
'水樹奈々,mizuki_nana',
'沢城みゆき,sawashiro_miyuki',
'日笠陽子,hikasa_yoko',
'南條愛乃,nanjo_yoshino',
'矢作紗友里,yahagi_saori',
'たかはし智秋,takahashi_chiaki',
'小岩井ことり,koiwai_kotori',
'後藤沙緒里,goto_saori',
'日高里菜,hidaka_rina',
'沼倉愛美,numakura_manami',
'徳井青空,tokui_sora',
'中島愛,nakajima_megumi',
'佐藤利奈,sato_rina',
'茅原実里,chiara_minori',
'小見川千明,omigawa_chiaki',
'平野綾,hirano_aya',
'儀武ゆう子,gibu_yuko',
'釘宮理恵,kugimiya_rie',
'後藤邑子,goto_yuko',
'坂本真綾,sakamoto_maya',
'瀬戸麻沙美,seto_asami',
'種田梨沙,taneda_risa',
'名塚佳織,naduka_kaori',
'野中藍,nonaka_ai',
'原田ひとみ,harada_hitomi',
'福圓美里,fukuen_misato,',
'堀江由衣,horie_yui',
'松来未祐,matsuki_miyu',
'三澤紗千香,misawa_sachika',
'水橋かおり,mizuhashi_kaori',
'洲崎綾,suzaki_aya',
'石原夏織,ishihara_kaori',
'スフィア,sphere',
'今井麻美,imai_asami',
'新谷良子,shintani_ryoko',
'ゆいかおり,yui_kaori',
'新田恵海,nitta_emi',
'久保ユリカ,kubo_yurika',
'伊藤静,ito_shizuka',
'赤崎千夏,akasaki_chinatsu',
'楠田亜衣奈,kusuda_aina',
'小清水亜美,koshimizu_ami',
'μ\'s,muse',
'金元寿子,kanemoto_hisako',
'プチミレディ,petit_milady',
'村川梨衣,murakawa_rie',
'中原麻衣,nakahara_mai',
'山本希望,yamamoto_mozomi',
'小林ゆう,kobayashi_yu',
'内田彩,uchida_aya',
'飯田里穂,ida_riho',
'浅野真澄,asano_masumi',
'西明日香,nishi_asuka',
'明坂聡美,akesaka_satomi',
'浅倉杏美,asakura_azumi',
'白石涼子,shiraishi_ryoko'
]

# DBオープン
db = sqlite3.connect(DB_FILE)
sql = 'insert into seiyu_tbl (name, name_e, birthday) values (?, ?, ?)'
for s in SEIYU:
	db.execute(sql, (s.split(",")[0].decode('utf-8'),s.split(",")[1],''))

db.commit()